import { Video } from "./video";
export const VIDEOS: Video[] = [
    {
        id: 1,
        name: "BACKSTAGE SPORTING | Sporting CP x Boavista FC",
        description: "Images from the game against Boavista FC",
        image: "assets/backstage1.jpg",
        url: "https://www.youtube.com/embed/0FYYLFwpwy8",
    },
    {
        id: 2,
        name: "Resumo | Liga Portugal: Sporting CP 6-1 Boavista FC",
        description: "Highlights from the match Sporting CP 6-1 Boavista FC",
        image: "assets/game1.jpg",
        url: "https://www.youtube.com/embed/ZtbRrd7xgPw",
    },
    {
        id: 3,
        name: "200 JOGOS DE RÚBEN AMORIM!",
        description: "Video to highlight 200 games of the coach Rúben Amorim",
        image: "assets/amorim.jpg",
        url: "https://www.youtube.com/embed/2_kzHlIOX1s",
    },
    {
        id: 4,
        name: "GYÖKERES | Sporting | Golos (2023/2024)",
        description: "All the goals of GYÖKERES so far",
        image: "assets/goals.jpg",
        url: "https://www.youtube.com/embed/xBd7ZmTcUFY",
    },
    {
        id: 5,
        name: "ADN de Leão 2.0 | Daniel Bragança",
        description: "ADN de Leão 2.0 | Daniel Bragança",
        image: "assets/adn_braganca.jpg",
        url: "https://www.youtube.com/embed/VqR9Kuh0w5g",
    },
    {
        id: 6,
        name: "Resumo | Taça de Portugal: Sporting CP 2-1 SL Benfica",
        description: "Resumo | Taça de Portugal: Sporting CP 2-1 SL Benfica",
        image: "assets/resumo_taca.jpg",
        url: "https://www.youtube.com/embed/O4H51_Jw_U0",
    },
    {
        id: 7,
        name: "150 JOGOS GONÇALO INÁCIO!",
        description: "150 JOGOS GONÇALO INÁCIO!",
        image: "assets/inacio_vid.jpg",
        url: "https://www.youtube.com/embed/tIYdFWiaito",
    },
    {
        id: 8,
        name: "BACKSTAGE SPORTING | Sporting CP x SC Braga",
        description: "BACKSTAGE SPORTING | Sporting CP x SC Braga",
        image: "assets/jogo_braga.jpg",
        url: "https://www.youtube.com/embed/BqlKQNreSJM",
    },
    {
        id: 9,
        name: "BACKSTAGE SPORTING | Sporting CP x FC Porto",
        description: "BACKSTAGE SPORTING | Sporting CP x FC Porto",
        image: "assets/jogo_porto.jpg",
        url: "https://www.youtube.com/embed/d0zv1jHcRR8",
    },
];